version: '3.8'

services:
  tester-backend:
    depends_on:
      - tester-database
    container_name: tester-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    environment:
      - SERVER_PORT=$PORT
      - NODE_ENV=$NODE_ENV
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOSTNAME=$DOCKER_HOSTNAME
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      - $DEBUG_LOCAL_PORT:$DEBUG_DOCKER_PORT
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - testerNetwork
    command: 'npm run start:dev'
    stdin_open: true
    tty: true

  tester-database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - testerNetwork

  tester-mongo-express:
    image: mongo-express
    container_name: tester-mongo-express
    depends_on:
      - tester-database
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$DB_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$DB_PASSWORD
      - ME_CONFIG_MONGODB_URL=mongodb://root:$DB_PASSWORD@$DOCKER_HOSTNAME:$DB_PORT/
    networks:
      - testerNetwork
networks:
  testerNetwork:
    driver: bridge

volumes:
  dbdata:
  node_modules:
